### ISSUE TITLE
 1.12.2 正向ws链接成功但是不发信息

### ISSUE THREAD

**Issue by Yummy-cookie** [17TheWord/MC_QQ_Spigot#22]
服务器启动时报错
![image](https://github.com/17TheWord/MC_QQ_Spigot/assets/114837513/41f9453f-918b-4054-b429-5a4677ff2dbf)

**Comment by 17TheWord** [comment]
给出服务端信息

**Comment by Yummy-cookie** [comment]
ws没有提示，机器人显示链接，游戏信息可以发QQ，QQ信息发不到游戏

**Comment by 17TheWord** [comment]
服务端是哪个啊Spigot、CatServer？

**Comment by Yummy-cookie** [comment]
CatServer

**Comment by 17TheWord** [comment]
尝试下这个，可以的话我推送至主分支 [MC_QQ_Spigot_1.14-latest-2.7.2.zip](https://github.com/user-attachments/files/16114884/MC_QQ_Spigot_1.14-latest-2.7.2.zip)

**Comment by 17TheWord** [comment]
#23 ，墨端请使用正向 `Websocket`
